[
    {
        "error": "Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.",
        "img_path": "../datasets/TUTFS/42/TD_RGB_E_5.jpg"
    },
    {
        "error": "Face could not be detected. Please confirm that the picture is a face photo or consider to set enforce_detection param to False.",
        "img_path": "../datasets/TUTFS/112/TD_RGB_E_5.jpg"
    }
]